/**/gate_yolo_node:
  ros__parameters:
    model_name: yolov11s_gate_20250522_1.engine
    conf: 0.25
    iou: 0.7
    agnostic_nms: true
    input_image_topic: color/image/orin
    output_detections_topic: gate/yolo/detections
    output_image_topic: gate/yolo/image

/**/symbol_yolo_node:
  ros__parameters:
    model_name: yolov11s_symbol_20250527_2.engine
    conf: 0.25
    iou: 0.7
    agnostic_nms: true
    input_image_topic: color/image/orin
    output_detections_topic: symbol/yolo/detections
    output_image_topic: symbol/yolo/image

/**/gate_pose_estimator_node:
  ros__parameters:
    camera_frame_id: auv4/front_cam_optical
    object_frame_id: wesley_please_come_lab
    camera_info_topic: color/camera_info
    detections_topic: gate/yolo/detections
